export const GET_ROOMS = 'GET_ROOMS';
export const POST_ROOM = 'POST_ROOM';
export const SUBSCRIBE_ROOM = 'SUBSCRIBE_ROOM';
export const SET_CURRENT_ROOM_ID = 'SET_CURRENT_ROOM_ID';
export const CREATE_ROOM = 'CREATE_ROOM';

export const GET_MESSAGES = 'GET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';